-- Run this SQL in Supabase SQL Editor before enabling the site integration.
create table if not exists public.sociopairs_users (
  username text primary key,
  gender text not null check (gender in ('female', 'male')),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.sociopairs_surveys (
  id bigint generated by default as identity primary key,
  author text not null references public.sociopairs_users(username) on delete cascade,
  target_gender text not null check (target_gender in ('female', 'male')),
  age_min integer not null check (age_min between 16 and 99),
  age_max integer not null check (age_max between 16 and 99),
  height_min integer not null check (height_min between 120 and 230),
  height_max integer not null check (height_max between 120 and 230),
  hair_length text not null,
  eye_color text not null,
  style text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.sociopairs_users enable row level security;
alter table public.sociopairs_surveys enable row level security;

-- GitHub Pages is fully client-side, so only the anon key should be exposed.
-- These policies allow the app to read/write research data while table constraints
-- prevent malformed rows. Do not expose private personal data with these policies.
drop policy if exists "sociopairs_users_select" on public.sociopairs_users;
create policy "sociopairs_users_select" on public.sociopairs_users for select to anon using (true);

drop policy if exists "sociopairs_users_insert" on public.sociopairs_users;
create policy "sociopairs_users_insert" on public.sociopairs_users for insert to anon with check (true);

drop policy if exists "sociopairs_users_update_gender" on public.sociopairs_users;
create policy "sociopairs_users_update_gender" on public.sociopairs_users for update to anon using (true) with check (true);

drop policy if exists "sociopairs_surveys_select" on public.sociopairs_surveys;
create policy "sociopairs_surveys_select" on public.sociopairs_surveys for select to anon using (true);

drop policy if exists "sociopairs_surveys_insert" on public.sociopairs_surveys;
create policy "sociopairs_surveys_insert" on public.sociopairs_surveys for insert to anon with check (true);
